name: Java Static Code Analysis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  static-code-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Cache Gradle user home
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-cache-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-cache-${{ runner.os }}-

      - name: Grant execute for gradlew
        run: chmod +x ./gradlew

      - name: Build (skip tests)
        run: ./gradlew clean build -x test --no-daemon

      - name: Run SpotBugs (main source set)
        run: ./gradlew spotbugsMain --no-daemon

      - name: Upload SpotBugs SARIF
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: build/reports/spotbugs/main.sarif
